### ISSUE TITLE
config.action_mailer.default_url_options not working

### ISSUE THREAD

**Issue by ricardopacheco** [fnando/rails-env#1]
Create a file: config/initializers/app.rb with content:

``` ruby
Rails.env.on(:development) do |config|
  config.action_mailer.default_url_options = { host: 'localhost:3000' }
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.delivery_method = :letter_opener
end
```

But, config.action_mailer.default_url_options not working, generating a follow message (with devise):

ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):

Rails: 4.2.1
Ruby: 2.2.2
Devise:  3.5.1

What happened?

**Comment by ricardopacheco** [comment]
Fix temporary:

Inside a block add a follow line:

``` ruby
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
```

it's works!

**Comment by fnando** [comment]
This behavior is soooo bizarre. Look at this file: https://gist.github.com/fnando/81b1e16b92caa779208e

I don't know why, but setting `config.action_mailer` outside the Application scope doesn't propagate changes to `ActionMailer::Base`. I'm investigating this. :/
